version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'my-user'
      MYSQL_PASSWORD: 'my-user-password'
      MYSQL_DATABASE: 'my-db'
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
     - db
    image: phpmyadmin/phpmyadmin:5.0
    ports:
     - '7777:80'
    environment:
      PMA_HOST: db

volumes:
  mysql_data:
